name: praktikum_6
description: "1. Mengimplementasikan CRUD dengan SQLite. 2. Mengintegrasikan push notification. 3. Menulis unit test dan widget test untuk memvalidasi fungsionalitas."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  path_provider: ^2.1.5
  flutter_local_notifications: ^19.0.0
  build_runner: ^2.4.15

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  mockito: ^5.4.5
  test: ^1.25.15
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
